CREATE DATABASE learnguitar;

use learnguitar;

CREATE TABLE user(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    photo VARCHAR(255) NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE post(
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    text VARCHAR(255) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_id FOREIGN KEY(user_id) REFERENCES user(id)
)